# Generated by Django 3.0.3 on 2020-04-13 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertiseTags',
            fields=[
                ('expertiseTagName', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='')),
                ('imageText', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('expertiseTags', models.ManyToManyField(to='home.ExpertiseTags')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('voteId', models.AutoField(primary_key=True, serialize=False)),
                ('positive', models.BooleanField()),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Post')),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SubTags',
            fields=[
                ('subTagName', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('expertiseTag', models.ManyToManyField(to='home.ExpertiseTags')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='assignedUserIds',
            field=models.ManyToManyField(related_name='assigned', to='home.Profile'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='home.SubTags'),
        ),
        migrations.AddField(
            model_name='post',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_user', to='home.Profile'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentId', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=1000)),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Post')),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Profile')),
            ],
        ),
    ]
