# Generated by Django 3.0.3 on 2020-04-14 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expertisetags',
            options={'verbose_name_plural': 'Expertise tags'},
        ),
        migrations.AlterModelOptions(
            name='subtags',
            options={'verbose_name_plural': 'Sub tags'},
        ),
        migrations.AlterModelOptions(
            name='votes',
            options={'verbose_name_plural': 'Votes'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
